# Site settings
title: Michelle Blom
email: michelle.blom@unimelb.edu.au
description: Academic webpage of Dr. Michelle Blom
baseurl: ""
url: ""

# Footer info
affiliation: >
    Michelle Blom<br/>
    Senior Research Fellow<br/>
    AI and Autonomy Lab<br/>
    University of Melbourne

location: >
  Melbourne Connect<br/>
  University of Melbourne<br/>
  Parkville, Australia, 3010

contact: >
    <a href="mailto:michelle.blom@unimelb.edu.au" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Michelle via email</a> <br/>
    <a href="https://github.com/sbryngelson/academic-website-template"><i class="fa fa-github fa-1x"></i> Use this site as a template!</a>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
  - name: research
  - name: software

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: ['jekyll/scholar']

scholar:

  last_name: Blom
  first_name: [Michelle]

  style: citesty
  locale: en

  source: /assets/
  bibliography: refs_Jan12_2023.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
